services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PW}"
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PW}"
      TZ: "${TZ}"
    platform: "linux/x86_64"

volumes:
  db-data: